# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-18 01:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ParticleHooks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
